server:
  port : 9090
spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/ssac?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.websocket.chat.mappers
  mapper-locations: mapper/**/*.xml